name: Publish
on:
  - workflow_dispatch
permissions:
  contents: read

concurrency:
  group: "publish"
  cancel-in-progress: false

env:
  DOCS_BUNDLE: docs.bundle
  DOCS_BUNDLE_ARTIFACT: docs-bundle

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Java
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          distribution: "temurin"
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Gradle Assemble
        run: ./gradlew assemble --info -S --show-version

  check:
    name: Check
    strategy:
      matrix:
        jdk: [ 22, 24 ]
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Java
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          distribution: "temurin"
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Gradle Check
        shell: bash
        run: ./gradlew check --info -S --show-version -Ptoolchain.test.version=${{ matrix.jdk }}

  build-docs:
    name: Build Documentation
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0

      - name: Install dependencies
        run: pip3 install --no-deps -r .github/workflows/mkdocs-requirements.txt

      - name: Configure git for mike
        shell: bash
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch origin gh-pages

      - name: Get Version
        id: version
        run: grep '^version=' gradle.properties >> $GITHUB_OUTPUT

      - name: Mike Deploy
        env:
          VERSION_NAME: ${{ steps.version.outputs.version }}
        run: mike deploy -u $VERSION_NAME latest

      - name: Create Bundle
        run: git bundle create ${{ env.DOCS_BUNDLE }} gh-pages

      - name: Upload workspace artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ${{ env.DOCS_BUNDLE_ARTIFACT }}
          path: ${{ env.DOCS_BUNDLE }}
          retention-days: 1

  build-artifact-bundle:
    name: Build Artifact Bundle
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Java
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          distribution: "temurin"
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Build Artifact Bundle
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew --init-script ./.github/init.gradle.kts artifactBundle --info -S --show-version

      - name: Upload Artifact Bundle
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: "artifact-bundle"
          path: "./build/libs/maven-artifact-bundle.tgz"

  central-upload:
    name: Upload to Central Portal
    needs: [build-artifact-bundle, build-docs]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact Bundle
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: "artifact-bundle"
          path: .

      - id: upload
        name: Upload to Central Portal
        uses: TheMrMilchmann/central-portal-actions/upload-deployment@49408323afaf26e74be8e9df84a7a4ca81615e3a # v1.0.0
        with:
          username: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          password: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
          bundle: ./maven-artifact-bundle.tgz
          publishing-type: "user-managed"
    outputs:
      deployment-id: ${{ steps.upload.outputs.deployment-id }}

  ghp-release:
    name: Release Documentation to GitHub Pages
    needs: [build-docs, central-upload]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Checkout
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: ${{ env.DOCS_BUNDLE_ARTIFACT }}
          path: .

      - name: Unpack git bundle
        run: |
          git fetch ${{ env.DOCS_BUNDLE }} gh-pages:gh-pages
          git switch --force gh-pages

      - name: Configure git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Push to GH Pages
        run: git push origin gh-pages

  central-release:
    name: Release to Central Portal
    needs: [central-upload, ghp-release]
    runs-on: ubuntu-latest
    steps:
      - name: Release to Central Portal
        uses: TheMrMilchmann/central-portal-actions/publish-deployment@49408323afaf26e74be8e9df84a7a4ca81615e3a # v1.0.0
        with:
          username: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          password: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
          deployment-id: ${{ needs.central-upload.outputs.deployment-id }}